apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: demo-graalvm-springboot
  name: graalvm-springboot
  namespace: parca
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-graalvm-springboot
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-graalvm-springboot
    spec:
      containers:
      - image: parca-demo:graalvm-springboot
        name: graalvm-springboot
        resources:
          limits:
            cpu: '100m'
            memory: '256Mi'
